test: Omit 'additionalProperties' from required properties
Since adding 'additionalProperties' to good-example.yaml, the tests are
failing:

FAIL: test_required_property_missing (__main__.TestDTMetaSchema) (k='additionalProperties')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test-dt-validate.py", line 47, in test_required_property_missing
    self.assertRaises(jsonschema.SchemaError, dtschema.DTValidator.check_schema, schema_tmp)
AssertionError: SchemaError not raised by check_schema

Add 'additionalProperties' to the list of optional properties. Really
this test needs to be reworked. It's fragile as it needs to be kept in
sync with the meta-schema. Rather than modifying a schema at run-time we
should probably have a set of expected fail schema files.

Signed-off-by: Rob Herring <robh@kernel.org>